/*
	Массив для перебора пиктограмм государственных флагов в спрайте (fg.css + fg.png)
	@author  Артём Поликарпов, artpolikarpov.ru (artpolikarpov@gmail.com)
*/
var fg = [
	['abkhazia', 'Abkhazia', 'Абхазия'],
	['ad', 'Andorra', 'Андорра'],
	['ae', 'United Arab Emirates', 'Объединённые Арабские Эмираты'],
	['af', 'Afghanistan', 'Афганистан'],
	['ag', 'Antigua and Barbuda', 'Антигуа и Барбуда'],
	['ai', 'Anguilla', 'Ангилья'],
	['al', 'Albania', 'Албания'],
	['am', 'Armenia', 'Армения'],
	['an', 'Netherlands Antilles', 'Нидерландские Антилы'],
	['ao', 'Angola', 'Ангола'],
	['aq', 'Antarctica', 'Антарктида'],
	['ar', 'Argentina', 'Аргентина'],
	['as', 'American Samoa', 'Американское Самоа'],
	['at', 'Austria', 'Австрия'],
	['au', 'Australia', 'Австралия'],
	['aw', 'Aruba', 'Аруба'],
	['ax', 'Aland Islands', 'Эландские острова'],
	['az', 'Azerbaijan', 'Азербайджан'],
	['ba', 'Bosnia and Herzegovina', 'Босния и Герцеговина'],
	['bb', 'Barbados', 'Барбадос'],
	['bd', 'Bangladesh', 'Бангладеш'],
	['be', 'Belgium', 'Бельгия'],
	['bf', 'Burkina Faso', 'Буркина Фасо'],
	['bg', 'Bulgaria', 'Болгария'],
	['bh', 'Bahrain', 'Бахрейн'],
	['bi', 'Burundi', 'Бурунди'],
	['bj', 'Benin', 'Бенин'],
	['bl', 'Saint Barthelemy', 'Сен-Бартельми'],
	['bm', 'Bermuda', 'Бермуды'],
	['bn', 'Brunei', 'Бруней'],
	['bo', 'Bolivia', 'Боливия'],
	['br', 'Brazil', 'Бразилия'],
	['bs', 'Bahamas', 'Багамы'],
	['bt', 'Bhutan', 'Бутан'],
	['bv', 'Bouvet Island', 'Остров Буве'],
	['bw', 'Botswana', 'Ботсвана'],
	['by', 'Belarus', 'Беларусь'],
	['bz', 'Belize', 'Белиз'],
	['ca', 'Canada', 'Канада'],
	['cc', 'Cocos (Keeling) Islands', 'Кокосовые (Килинг) острова'],
	['cd', 'Congo (Democratic Republic)', 'Конго (Демократическая Республика)'],
	['cf', 'Central African Republic', 'Центральноафриканская Республика'],
	['cg', 'Congo', 'Конго'],
	['ch', 'Switzerland', 'Швейцария'],
	['ci', 'Cote d’Ivoire', 'Кот-д’Ивуар'],
	['ck', 'Cook Islands', 'Острова Кука'],
	['cl', 'Chile', 'Чили'],
	['cm', 'Cameroon', 'Камерун'],
	['cn', 'China', 'Китай'],
	['co', 'Colombia', 'Колумбия'],
	['cr', 'Costa Rica', 'Коста-Рика'],
	['cu', 'Cuba', 'Куба'],
	['cv', 'Cape Verde', 'Кабо-Верде'],
	['cx', 'Christmas Island', 'Остров Рождества'],
	['cy', 'Cyprus', 'Кипр'],
	['cz', 'Czech Republic', 'Чехия'],
	['de', 'Germany', 'Германия'],
	['dj', 'Djibouti', 'Джибути'],
	['dk', 'Denmark', 'Дания'],
	['dm', 'Dominica', 'Доминика'],
	['do', 'Dominican Republic', 'Доминиканская Республика'],
	['dz', 'Algeria', 'Алжир'],
	['ec', 'Ecuador', 'Эквадор'],
	['ee', 'Estonia', 'Эстония'],
	['eg', 'Egypt', 'Египет'],
	['eh', 'Western Sahara', 'Западная Сахара'],
	['er', 'Eritrea', 'Эритрея'],
	['es-ce', 'Ceuta', 'Сеута'],
	['es-ml', 'Melilla', 'Мельлия'],
	['es', 'Spain', 'Испания'],
	['et', 'Ethiopia', 'Эфиопия'],
	['eu', 'European Union', 'Евросоюз'],
	['fi', 'Finland', 'Финляндия'],
	['fj', 'Fiji', 'Фиджи'],
	['fk', 'Falkland Islands (Malvinas)', 'Фолклендские острова (Мальвинские)'],
	['fm', 'Micronesia', 'Микронезия'],
	['fo', 'Faroe Islands', 'Фарерские острова'],
	['fr', 'France', 'Франция'],
	['ga', 'Gabon', 'Габон'],
	['gb', 'United Kingdom', 'Великобритания'],
	['gd', 'Grenada', 'Гренада'],
	['ge', 'Georgia', 'Грузия'],
	['gf', 'French Guiana', 'Французская Гвиана'],
	['gg', 'Guernsey', 'Гернси'],
	['gh', 'Ghana', 'Гана'],
	['gi', 'Gibraltar', 'Гибралтар'],
	['gl', 'Greenland', 'Гренландия'],
	['gm', 'Gambia', 'Гамбия'],
	['gn', 'Guinea', 'Гвинея'],
	['gp', 'Guadeloupe', 'Гваделупа'],
	['gq', 'Equatorial Guinea', 'Экваториальная Гвинея'],
	['gr', 'Greece', 'Греция'],
	['gs', 'South Georgia and the South Sandwich Islands', 'Южная Джорджия и Южные Сандвичевы острова'],
	['gt', 'Guatemala', 'Гватемала'],
	['gu', 'Guam', 'Гуам'],
	['gw', 'Guinea-Bissau', 'Гвинея-Бисау'],
	['gy', 'Guyana', 'Гайана'],
	['hk', 'Hong Kong', 'Гонконг'],
	['hm', 'Heard Island and McDonald Islands', 'Остров Херд и острова Макдональд'],
	['hn', 'Honduras', 'Гондурас'],
	['hr', 'Croatia', 'Хорватия'],
	['ht', 'Haiti', 'Гаити'],
	['hu', 'Hungary', 'Венгрия'],
	['ic', 'Canary Islands', 'Канарские острова'],
	['id', 'Indonesia', 'Индонезия'],
	['ie', 'Ireland', 'Ирландия'],
	['il', 'Israel', 'Израиль'],
	['im', 'Isle of Man', 'Остров Мэн'],
	['in', 'India', 'Индия'],
	['io', 'British Indian Ocean Territory', 'Британская территория в Индийском океане'],
	['iq', 'Iraq', 'Ирак'],
	['ir', 'Iran', 'Иран'],
	['is', 'Iceland', 'Исландия'],
	['it', 'Italy', 'Италия'],
	['je', 'Jersey', 'Джерси'],
	['jm', 'Jamaica', 'Ямайка'],
	['jo', 'Jordan', 'Иордания'],
	['jp', 'Japan', 'Япония'],
	['ke', 'Kenya', 'Кения'],
	['kg', 'Kyrgyzstan', 'Киргизия'],
	['kh', 'Cambodia', 'Камбоджа'],
	['ki', 'Kiribati', 'Кирибати'],
	['km', 'Comoros', 'Коморы'],
	['kn', 'Saint Kitts and Nevis', 'Сент-Китс и Невис'],
	['kosovo', 'Kosovo', 'Косово'],
	['kp', 'North Korea', 'Северная Корея'],
	['kr', 'South Korea', 'Южная Корея'],
	['kw', 'Kuwait', 'Кувейт'],
	['ky', 'Cayman Islands', 'Острова Кайман'],
	['kz', 'Kazakhstan', 'Казахстан'],
	['la', 'Laos', 'Лаос'],
	['lb', 'Lebanon', 'Ливан'],
	['lc', 'Saint Lucia', 'Сент-Люсия'],
	['li', 'Liechtenstein', 'Лихтенштейн'],
	['lk', 'Sri Lanka', 'Шри-Ланка'],
	['lr', 'Liberia', 'Либерия'],
	['ls', 'Lesotho', 'Лесото'],
	['lt', 'Lithuania', 'Литва'],
	['lu', 'Luxembourg', 'Люксембург'],
	['lv', 'Latvia', 'Латвия'],
	['ly', 'Libya', 'Ливия'],
	['ma', 'Morocco', 'Марокко'],
	['mc', 'Monaco', 'Монако'],
	['md', 'Moldova', 'Молдова'],
	['me', 'Montenegro', 'Черногория'],
	['mf', 'Saint Martin', 'Остров Святого Мартина'],
	['mg', 'Madagascar', 'Мадагаскар'],
	['mh', 'Marshall Islands', 'Маршалловы острова'],
	['mk', 'Macedonia', 'Македония'],
	['ml', 'Mali', 'Мали'],
	['mm', 'Myanmar', 'Мьянма'],
	['mn', 'Mongolia', 'Монголия'],
	['mo', 'Macao', 'Макао'],
	['mp', 'Northern Mariana Islands', 'Северные Марианские острова'],
	['mq', 'Martinique', 'Мартиника'],
	['mr', 'Mauritania', 'Мавритания'],
	['ms', 'Montserrat', 'Монтсеррат'],
	['mt', 'Malta', 'Мальта'],
	['mu', 'Mauritius', 'Маврикий'],
	['mv', 'Maldives', 'Мальдивы'],
	['mw', 'Malawi', 'Малави'],
	['mx', 'Mexico', 'Мексика'],
	['my', 'Malaysia', 'Малайзия'],
	['mz', 'Mozambique', 'Мозамбик'],
	['na', 'Namibia', 'Намибия'],
	['nc', 'New Caledonia', 'Новая Каледония'],
	['ne', 'Niger', 'Нигер'],
	['nf', 'Norfolk Island', 'Остров Норфолк'],
	['ng', 'Nigeria', 'Нигерия'],
	['ni', 'Nicaragua', 'Никарагуа'],
	['nkr', 'Nagorno-Karabakh Republic', 'Нагорно-Карабахская Республика'],
	['nl', 'Netherlands', 'Нидерланды'],
	['no', 'Norway', 'Норвегия'],
	['np', 'Nepal', 'Непал'],
	['nr', 'Nauru', 'Науру'],
	['nu', 'Niue', 'Ниуэ'],
	['nz', 'New Zealand', 'Новая Зеландия'],
	['om', 'Oman', 'Оман'],
	['pa', 'Panama', 'Панама'],
	['pe', 'Peru', 'Перу'],
	['pf', 'French Polynesia', 'Французская Полинезия'],
	['pg', 'Papua New Guinea', 'Папуа-Новая Гвинея'],
	['ph', 'Philippines', 'Филиппины'],
	['pk', 'Pakistan', 'Пакистан'],
	['pl', 'Poland', 'Польша'],
	['pm', 'Saint Pierre and Miquelon', 'Сен-Пьер и Микелон'],
	['pn', 'Pitcairn', 'Питкерн'],
	['pr', 'Puerto Rico', 'Пуэрто-Рико'],
	['ps', 'Palestinian Territory', 'Палестинская автономия'],
	['pt', 'Portugal', 'Португалия'],
	['pw', 'Palau', 'Палау'],
	['py', 'Paraguay', 'Парагвай'],
	['qa', 'Qatar', 'Катар'],
	['re', 'Reunion', 'Реюньон'],
	['ro', 'Romania', 'Румыния'],
	['rs', 'Serbia', 'Сербия'],
	['ru', 'Russian Federation', 'Россия'],
	['rw', 'Rwanda', 'Руанда'],
	['sa', 'Saudi Arabia', 'Саудовская Аравия'],
	['sb', 'Solomon Islands', 'Соломоновы острова'],
	['sc', 'Seychelles', 'Сейшелы'],
	['sd', 'Sudan', 'Судан'],
	['se', 'Sweden', 'Швеция'],
	['sg', 'Singapore', 'Сингапур'],
	['sh', 'Saint Helena', 'Святая Елена'],
	['si', 'Slovenia', 'Словения'],
	['sj', 'Svalbard and Jan Mayen', 'Шпицберген и Ян Майен'],
	['sk', 'Slovakia', 'Словакия'],
	['sl', 'Sierra Leone', 'Сьерра-Леоне'],
	['sm', 'San Marino', 'Сан-Марино'],
	['sn', 'Senegal', 'Сенегал'],
	['so', 'Somalia', 'Сомали'],
	['south-ossetia', 'South Ossetia', 'Южная Осетия'],
	['sr', 'Suriname', 'Суринам'],
	['st', 'Sao Tome and Principe', 'Сан-Томе и Принсипи'],
	['sv', 'El Salvador', 'Эль-Сальвадор'],
	['sy', 'Syrian Arab Republic', 'Сирийская Арабская Республика'],
	['sz', 'Swaziland', 'Свазиленд'],
	['tc', 'Turks and Caicos Islands', 'Острова Теркс и Кайкос'],
	['td', 'Chad', 'Чад'],
	['tf', 'French Southern Territories', 'Французские Южные территории'],
	['tg', 'Togo', 'Того'],
	['th', 'Thailand', 'Таиланд'],
	['tj', 'Tajikistan', 'Таджикистан'],
	['tk', 'Tokelau', 'Токелау'],
	['tl', 'Timor-Leste', 'Тимор-Лесте'],
	['tm', 'Turkmenistan', 'Туркмения'],
	['tn', 'Tunisia', 'Тунис'],
	['to', 'Tonga', 'Тонга'],
	['tr', 'Turkey', 'Турция'],
	['tt', 'Trinidad and Tobago', 'Тринидад и Тобаго'],
	['tv', 'Tuvalu', 'Тувалу'],
	['tw', 'Taiwan', 'Тайвань'],
	['tz', 'Tanzania', 'Танзания'],
	['ua', 'Ukraine', 'Украина'],
	['ug', 'Uganda', 'Уганда'],
	['um', 'United States Minor Outlying Islands', 'Малые Тихоокеанские отдаленные острова Соединенных Штатов'],
	['us', 'United States', 'Соединенные Штаты Америки'],
	['uy', 'Uruguay', 'Уругвай'],
	['uz', 'Uzbekistan', 'Узбекистан'],
	['va', 'Holy See (Vatican)', 'Папский Престол (Ватикан)'],
	['vc', 'Saint Vincent and the Grenadines', 'Сент-Винсент и Гренадины'],
	['ve', 'Venezuela', 'Венесуэла'],
	['vg', 'Virgin Islands (British)', 'Виргинские острова (Британские)'],
	['vi', 'Virgin Islands (U.S.)', 'Виргинские острова (США)'],
	['vn', 'Viet Nam', 'Вьетнам'],
	['vu', 'Vanuatu', 'Вануату'],
	['wf', 'Wallis and Futuna', 'Уоллис и Футуна'],
	['ws', 'Samoa', 'Самоа'],
	['ye', 'Yemen', 'Йемен'],
	['yt', 'Mayotte', 'Майотта'],
	['za', 'South Africa', 'Южная Африка'],
	['zm', 'Zambia', 'Замбия'],
	['zw', 'Zimbabwe', 'Зимбабве']
]