/*
	Массив для перебора пиктограмм государственных флагов в спрайте (fg.css + fg.png)
	v0.1, 8 июля 2011
	@author  Артём Поликарпов, artpolikarpov.ru (artpolikarpov@gmail.com)
	Набор распостраняется на условиях лицензии CC-BY-SA
*/
var fg = [
	['ABKHAZIA', 'Abkhazia', 'Абхазия'],
	['AD', 'Andorra', 'Андорра'],
	['AE', 'United Arab Emirates', 'Объединённые Арабские Эмираты'],
	['AF', 'Afghanistan', 'Афганистан'],
	['AG', 'Antigua and Barbuda', 'Антигуа и Барбуда'],
	['AI', 'Anguilla', 'Ангилья'],
	['AL', 'Albania', 'Албания'],
	['AM', 'Armenia', 'Армения'],
	['AN', 'Netherlands Antilles', 'Нидерландские Антилы'],
	['AO', 'Angola', 'Ангола'],
	['AQ', 'Antarctica', 'Антарктида'],
	['AR', 'Argentina', 'Аргентина'],
	['AS', 'American Samoa', 'Американское Самоа'],
	['AT', 'Austria', 'Австрия'],
	['AU', 'Australia', 'Австралия'],
	['AW', 'Aruba', 'Аруба'],
	['AX', 'Aland Islands', 'Эландские острова'],
	['AZ', 'Azerbaijan', 'Азербайджан'],
	['BA', 'Bosnia and Herzegovina', 'Босния и Герцеговина'],
	['BB', 'Barbados', 'Барбадос'],
	['BD', 'Bangladesh', 'Бангладеш'],
	['BE', 'Belgium', 'Бельгия'],
	['BF', 'Burkina Faso', 'Буркина Фасо'],
	['BG', 'Bulgaria', 'Болгария'],
	['BH', 'Bahrain', 'Бахрейн'],
	['BI', 'Burundi', 'Бурунди'],
	['BJ', 'Benin', 'Бенин'],
	['BL', 'Saint Barthelemy', 'Сен-Бартельми'],
	['BM', 'Bermuda', 'Бермуды'],
	['BN', 'Brunei', 'Бруней'],
	['BO', 'Bolivia', 'Боливия'],
	['BR', 'Brazil', 'Бразилия'],
	['BS', 'Bahamas', 'Багамы'],
	['BT', 'Bhutan', 'Бутан'],
	['BV', 'Bouvet Island', 'Остров Буве'],
	['BW', 'Botswana', 'Ботсвана'],
	['BY', 'Belarus', 'Беларусь'],
	['BZ', 'Belize', 'Белиз'],
	['CA', 'Canada', 'Канада'],
	['CC', 'Cocos (Keeling) Islands', 'Кокосовые (Килинг) острова'],
	['CD', 'Congo (Democratic Republic)', 'Конго (Демократическая Республика)'],
	['CF', 'Central African Republic', 'Центральноафриканская Республика'],
	['CG', 'Congo', 'Конго'],
	['CH', 'Switzerland', 'Швейцария'],
	['CI', 'Cote d’Ivoire', 'Кот-д’Ивуар'],
	['CK', 'Cook Islands', 'Острова Кука'],
	['CL', 'Chile', 'Чили'],
	['CM', 'Cameroon', 'Камерун'],
	['CN', 'China', 'Китай'],
	['CO', 'Colombia', 'Колумбия'],
	['CR', 'Costa Rica', 'Коста-Рика'],
	['CU', 'Cuba', 'Куба'],
	['CV', 'Cape Verde', 'Кабо-Верде'],
	['CX', 'Christmas Island', 'Остров Рождества'],
	['CY', 'Cyprus', 'Кипр'],
	['CZ', 'Czech Republic', 'Чехия'],
	['DE', 'Germany', 'Германия'],
	['DJ', 'Djibouti', 'Джибути'],
	['DK', 'Denmark', 'Дания'],
	['DM', 'Dominica', 'Доминика'],
	['DO', 'Dominican Republic', 'Доминиканская Республика'],
	['DZ', 'Algeria', 'Алжир'],
	['EC', 'Ecuador', 'Эквадор'],
	['EE', 'Estonia', 'Эстония'],
	['EG', 'Egypt', 'Египет'],
	['EH', 'Western Sahara', 'Западная Сахара'],
	['ER', 'Eritrea', 'Эритрея'],
	['ES-CE', 'Ceuta', 'Сеута'],
	['ES-ML', 'Melilla', 'Мельлия'],
	['ES', 'Spain', 'Испания'],
	['ET', 'Ethiopia', 'Эфиопия'],
	['EU', 'European Union', 'Евросоюз'],
	['FI', 'Finland', 'Финляндия'],
	['FJ', 'Fiji', 'Фиджи'],
	['FK', 'Falkland Islands (Malvinas)', 'Фолклендские острова (Мальвинские)'],
	['FM', 'Micronesia', 'Микронезия'],
	['FO', 'Faroe Islands', 'Фарерские острова'],
	['FR', 'France', 'Франция'],
	['GA', 'Gabon', 'Габон'],
	['GB', 'United Kingdom', 'Великобритания'],
	['GD', 'Grenada', 'Гренада'],
	['GE', 'Georgia', 'Грузия'],
	['GF', 'French Guiana', 'Французская Гвиана'],
	['GG', 'Guernsey', 'Гернси'],
	['GH', 'Ghana', 'Гана'],
	['GI', 'Gibraltar', 'Гибралтар'],
	['GL', 'Greenland', 'Гренландия'],
	['GM', 'Gambia', 'Гамбия'],
	['GN', 'Guinea', 'Гвинея'],
	['GP', 'Guadeloupe', 'Гваделупа'],
	['GQ', 'Equatorial Guinea', 'Экваториальная Гвинея'],
	['GR', 'Greece', 'Греция'],
	['GS', 'South Georgia and the South Sandwich Islands', 'Южная Джорджия и Южные Сандвичевы острова'],
	['GT', 'Guatemala', 'Гватемала'],
	['GU', 'Guam', 'Гуам'],
	['GW', 'Guinea-Bissau', 'Гвинея-Бисау'],
	['GY', 'Guyana', 'Гайана'],
	['HK', 'Hong Kong', 'Гонконг'],
	['HM', 'Heard Island and McDonald Islands', 'Остров Херд и острова Макдональд'],
	['HN', 'Honduras', 'Гондурас'],
	['HR', 'Croatia', 'Хорватия'],
	['HT', 'Haiti', 'Гаити'],
	['HU', 'Hungary', 'Венгрия'],
	['IC', 'Canary Islands', 'Канарские острова'],
	['ID', 'Indonesia', 'Индонезия'],
	['IE', 'Ireland', 'Ирландия'],
	['IL', 'Israel', 'Израиль'],
	['IM', 'Isle of Man', 'Остров Мэн'],
	['IN', 'India', 'Индия'],
	['IO', 'British Indian Ocean Territory', 'Британская территория в Индийском океане'],
	['IQ', 'Iraq', 'Ирак'],
	['IR', 'Iran', 'Иран'],
	['IS', 'Iceland', 'Исландия'],
	['IT', 'Italy', 'Италия'],
	['JE', 'Jersey', 'Джерси'],
	['JM', 'Jamaica', 'Ямайка'],
	['JO', 'Jordan', 'Иордания'],
	['JP', 'Japan', 'Япония'],
	['KE', 'Kenya', 'Кения'],
	['KG', 'Kyrgyzstan', 'Киргизия'],
	['KH', 'Cambodia', 'Камбоджа'],
	['KI', 'Kiribati', 'Кирибати'],
	['KM', 'Comoros', 'Коморы'],
	['KN', 'Saint Kitts and Nevis', 'Сент-Китс и Невис'],
	['KOSOVO', 'Kosovo', 'Косово'],
	['KP', 'North Korea', 'Северная Корея'],
	['KR', 'South Korea', 'Южная Корея'],
	['KW', 'Kuwait', 'Кувейт'],
	['KY', 'Cayman Islands', 'Острова Кайман'],
	['KZ', 'Kazakhstan', 'Казахстан'],
	['LA', 'Laos', 'Лаос'],
	['LB', 'Lebanon', 'Ливан'],
	['LC', 'Saint Lucia', 'Сент-Люсия'],
	['LI', 'Liechtenstein', 'Лихтенштейн'],
	['LK', 'Sri Lanka', 'Шри-Ланка'],
	['LR', 'Liberia', 'Либерия'],
	['LS', 'Lesotho', 'Лесото'],
	['LT', 'Lithuania', 'Литва'],
	['LU', 'Luxembourg', 'Люксембург'],
	['LV', 'Latvia', 'Латвия'],
	['LY', 'Libya', 'Ливия'],
	['MA', 'Morocco', 'Марокко'],
	['MC', 'Monaco', 'Монако'],
	['MD', 'Moldova', 'Молдова'],
	['ME', 'Montenegro', 'Черногория'],
	['MF', 'Saint Martin', 'Остров Святого Мартина'],
	['MG', 'Madagascar', 'Мадагаскар'],
	['MH', 'Marshall Islands', 'Маршалловы острова'],
	['MK', 'Macedonia', 'Македония'],
	['ML', 'Mali', 'Мали'],
	['MM', 'Myanmar', 'Мьянма'],
	['MN', 'Mongolia', 'Монголия'],
	['MO', 'Macao', 'Макао'],
	['MP', 'Northern Mariana Islands', 'Северные Марианские острова'],
	['MQ', 'Martinique', 'Мартиника'],
	['MR', 'Mauritania', 'Мавритания'],
	['MS', 'Montserrat', 'Монтсеррат'],
	['MT', 'Malta', 'Мальта'],
	['MU', 'Mauritius', 'Маврикий'],
	['MV', 'Maldives', 'Мальдивы'],
	['MW', 'Malawi', 'Малави'],
	['MX', 'Mexico', 'Мексика'],
	['MY', 'Malaysia', 'Малайзия'],
	['MZ', 'Mozambique', 'Мозамбик'],
	['NA', 'Namibia', 'Намибия'],
	['NC', 'New Caledonia', 'Новая Каледония'],
	['NE', 'Niger', 'Нигер'],
	['NF', 'Norfolk Island', 'Остров Норфолк'],
	['NG', 'Nigeria', 'Нигерия'],
	['NI', 'Nicaragua', 'Никарагуа'],
	['NKR', 'Nagorno-Karabakh Republic', 'Нагорно-Карабахская Республика'],
	['NL', 'Netherlands', 'Нидерланды'],
	['NO', 'Norway', 'Норвегия'],
	['NP', 'Nepal', 'Непал'],
	['NR', 'Nauru', 'Науру'],
	['NU', 'Niue', 'Ниуэ'],
	['NZ', 'New Zealand', 'Новая Зеландия'],
	['OM', 'Oman', 'Оман'],
	['PA', 'Panama', 'Панама'],
	['PE', 'Peru', 'Перу'],
	['PF', 'French Polynesia', 'Французская Полинезия'],
	['PG', 'Papua New Guinea', 'Папуа-Новая Гвинея'],
	['PH', 'Philippines', 'Филиппины'],
	['PK', 'Pakistan', 'Пакистан'],
	['PL', 'Poland', 'Польша'],
	['PM', 'Saint Pierre and Miquelon', 'Сен-Пьер и Микелон'],
	['PN', 'Pitcairn', 'Питкерн'],
	['PR', 'Puerto Rico', 'Пуэрто-Рико'],
	['PS', 'Palestinian Territory', 'Палестинская автономия'],
	['PT', 'Portugal', 'Португалия'],
	['PW', 'Palau', 'Палау'],
	['PY', 'Paraguay', 'Парагвай'],
	['QA', 'Qatar', 'Катар'],
	['RE', 'Reunion', 'Реюньон'],
	['RO', 'Romania', 'Румыния'],
	['RS', 'Serbia', 'Сербия'],
	['RU', 'Russian Federation', 'Россия'],
	['RW', 'Rwanda', 'Руанда'],
	['SA', 'Saudi Arabia', 'Саудовская Аравия'],
	['SB', 'Solomon Islands', 'Соломоновы острова'],
	['SC', 'Seychelles', 'Сейшелы'],
	['SD', 'Sudan', 'Судан'],
	['SE', 'Sweden', 'Швеция'],
	['SG', 'Singapore', 'Сингапур'],
	['SH', 'Saint Helena', 'Святая Елена'],
	['SI', 'Slovenia', 'Словения'],
	['SJ', 'Svalbard and Jan Mayen', 'Шпицберген и Ян Майен'],
	['SK', 'Slovakia', 'Словакия'],
	['SL', 'Sierra Leone', 'Сьерра-Леоне'],
	['SM', 'San Marino', 'Сан-Марино'],
	['SN', 'Senegal', 'Сенегал'],
	['SO', 'Somalia', 'Сомали'],
	['SOUTH-OSSETIA', 'South Ossetia', 'Южная Осетия'],
	['SR', 'Suriname', 'Суринам'],
	['ST', 'Sao Tome and Principe', 'Сан-Томе и Принсипи'],
	['SV', 'El Salvador', 'Эль-Сальвадор'],
	['SY', 'Syrian Arab Republic', 'Сирийская Арабская Республика'],
	['SZ', 'Swaziland', 'Свазиленд'],
	['TC', 'Turks and Caicos Islands', 'Острова Теркс и Кайкос'],
	['TD', 'Chad', 'Чад'],
	['TF', 'French Southern Territories', 'Французские Южные территории'],
	['TG', 'Togo', 'Того'],
	['TH', 'Thailand', 'Таиланд'],
	['TJ', 'Tajikistan', 'Таджикистан'],
	['TK', 'Tokelau', 'Токелау'],
	['TL', 'Timor-Leste', 'Тимор-Лесте'],
	['TM', 'Turkmenistan', 'Туркмения'],
	['TN', 'Tunisia', 'Тунис'],
	['TO', 'Tonga', 'Тонга'],
	['TR', 'Turkey', 'Турция'],
	['TT', 'Trinidad and Tobago', 'Тринидад и Тобаго'],
	['TV', 'Tuvalu', 'Тувалу'],
	['TW', 'Taiwan', 'Тайвань'],
	['TZ', 'Tanzania', 'Танзания'],
	['UA', 'Ukraine', 'Украина'],
	['UG', 'Uganda', 'Уганда'],
	['UM', 'United States Minor Outlying Islands', 'Малые Тихоокеанские отдаленные острова Соединенных Штатов'],
	['US', 'United States', 'Соединенные Штаты Америки'],
	['UY', 'Uruguay', 'Уругвай'],
	['UZ', 'Uzbekistan', 'Узбекистан'],
	['VA', 'Holy See (Vatican)', 'Папский Престол (Ватикан)'],
	['VC', 'Saint Vincent and the Grenadines', 'Сент-Винсент и Гренадины'],
	['VE', 'Venezuela', 'Венесуэла'],
	['VG', 'Virgin Islands (British)', 'Виргинские острова (Британские)'],
	['VI', 'Virgin Islands (U.S.)', 'Виргинские острова (США)'],
	['VN', 'Viet Nam', 'Вьетнам'],
	['VU', 'Vanuatu', 'Вануату'],
	['WF', 'Wallis and Futuna', 'Уоллис и Футуна'],
	['WS', 'Samoa', 'Самоа'],
	['YE', 'Yemen', 'Йемен'],
	['YT', 'Mayotte', 'Майотта'],
	['ZA', 'South Africa', 'Южная Африка'],
	['ZM', 'Zambia', 'Замбия'],
	['ZW', 'Zimbabwe', 'Зимбабве']
]